{
 "title": "Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Number of Orders Placed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(order_placed_total) or vector(0)",
     "legendFormat": "Orders"
    }
   ]
  },
  {
   "title": "Number of Orfers Failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(order_failed_total) or vector(0)",
     "legendFormat": "Orders"
    }
   ]
  },
  {
   "title": "Order Error Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(order_error_rate_percent[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Basket to Order Conversion Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(order_placed_total) / sum(basket_created_count_total)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Order Value (€)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monetary_value_orders_currency_total) / sum(order_placed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Value",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monetary_value_orders_currency_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Order Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(order_processing_duration_ms_milliseconds_sum[5m]) / rate(order_processing_duration_ms_milliseconds_count[5m])",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Average Payment Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(payment_processing_time_ms_milliseconds_sum[5m]) / rate(payment_processing_time_ms_milliseconds_count[5m])",
     "legendFormat": "Time"
    }
   ]
  }
 ]
}